#!/usr/bin/env npx tsx
/**
 * Drizzle ORMスキーマから完全なGraphQLスキーマを自動生成するスクリプト
 *
 * Database-Firstアプローチ:
 * 1. Drizzleスキーマ（src/db/schema.ts）を読み込む
 * 2. 完全なGraphQLスキーマ（型 + Query + Mutation + Input）を生成
 * 3. schema.graphql を上書き（またはマージ）
 *
 * 使用方法:
 *   npm run schema:generate-from-db
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

// Drizzleの型をGraphQL型にマッピング
const typeMapping: Record<string, string> = {
	bigserial: "Int!",
	bigint: "Int!",
	integer: "Int!",
	varchar: "String!",
	text: "String!",
	boolean: "Boolean!",
	date: "String!",
	timestamp: "String!",
	uuid: "String!",
};

const nullableTypeMapping: Record<string, string> = {
	bigserial: "Int",
	bigint: "Int",
	integer: "Int",
	varchar: "String",
	text: "String",
	boolean: "Boolean",
	date: "String",
	timestamp: "String",
	uuid: "String",
};

interface ColumnInfo {
	name: string;
	type: string;
	isNotNull: boolean;
	isArray: boolean;
	isPrimary: boolean;
	isAutoGenerated: boolean; // primaryKey() や default() がある場合
}

interface TableInfo {
	name: string;
	graphqlName: string;
	columns: ColumnInfo[];
	foreignKeys: ForeignKeyInfo[];
}

interface ForeignKeyInfo {
	columnName: string;
	referencedTable: string;
	referencedGraphQLType: string;
}

/**
 * テーブル名をGraphQL型名に変換
 */
function toGraphQLTypeName(tableName: string): string {
	// 複数形を単数形に変換
	let singular = tableName;
	if (tableName.endsWith("ies")) {
		singular = `${tableName.slice(0, -3)}y`;
	} else if (tableName.endsWith("ses")) {
		singular = tableName.slice(0, -2);
	} else if (tableName.endsWith("s") && !tableName.endsWith("ss")) {
		singular = tableName.slice(0, -1);
	}

	// キャメルケースをパスカルケースに変換
	const parts = singular.split(/(?=[A-Z])/);
	let result = parts
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");

	// 特殊ケースの修正
	if (result === "MidtermHealthPurpos") {
		result = "MidtermHealthPurpose";
	}
	if (result === "PtSession") {
		result = "PTSession";
	}
	if (result === "PtSessionItem") {
		result = "PTSessionItem";
	}

	return result;
}

/**
 * テーブル名をGraphQL Query名に変換（camelCase）
 */
function toGraphQLQueryName(tableName: string): string {
	// キャメルケースを維持
	return tableName.charAt(0).toLowerCase() + tableName.slice(1);
}

/**
 * 外部キーを検出
 */
function detectForeignKeys(
	tableName: string,
	columns: ColumnInfo[],
	allTables: string[],
): ForeignKeyInfo[] {
	const foreignKeys: ForeignKeyInfo[] = [];

	for (const column of columns) {
		// カラム名から外部キーを推測
		// 例: clientId -> clients, userId -> users, ptSessionId -> ptSessions
		const match = column.name.match(/^(.+?)(Id|_id)$/i);
		if (match) {
			const baseName = match[1];
			// 複数形に変換
			let pluralName = baseName;
			if (!pluralName.endsWith("s")) {
				if (pluralName.endsWith("y")) {
					pluralName = `${pluralName.slice(0, -1)}ies`;
				} else {
					pluralName = `${pluralName}s`;
				}
			}

			// テーブル名の候補を探す
			const candidateTable = allTables.find(
				(t) =>
					t.toLowerCase() === pluralName.toLowerCase() ||
					t.toLowerCase() === baseName.toLowerCase(),
			);

			if (candidateTable) {
				foreignKeys.push({
					columnName: column.name,
					referencedTable: candidateTable,
					referencedGraphQLType: toGraphQLTypeName(candidateTable),
				});
			}
		}
	}

	return foreignKeys;
}

/**
 * スキーマファイルをパース
 */
function parseSchemaFile(schemaContent: string): TableInfo[] {
	const tables: TableInfo[] = [];

	const tableRegex =
		/export const (\w+) = pgTable\("(\w+)",\s*\{([\s\S]*?)\}\);/g;

	const tableMatches = Array.from(schemaContent.matchAll(tableRegex));
	const tableNames = tableMatches.map((m) => m[1]);

	for (const match of tableMatches) {
		const [, variableName, , columnsBlock] = match;
		const columns: ColumnInfo[] = [];

		const columnStarts: number[] = [];
		const colStartRegex = /^\s*(\w+):\s*\w+\(/gm;

		for (const colStartMatch of columnsBlock.matchAll(colStartRegex)) {
			columnStarts.push(colStartMatch.index ?? 0);
		}

		for (let i = 0; i < columnStarts.length; i++) {
			const start = columnStarts[i];
			const end = columnStarts[i + 1] ?? columnsBlock.length;
			const colDef = columnsBlock.slice(start, end);

			const colMatch = colDef.match(/^\s*(\w+):\s*(\w+)\(/);

			if (colMatch) {
				const [, colName, colType] = colMatch;

				const isNotNull =
					colDef.includes(".notNull()") || colDef.includes(".primaryKey()");
				const isArray = colDef.includes(".array()");
				const isPrimary = colDef.includes(".primaryKey()");
				const isAutoGenerated =
					isPrimary ||
					colDef.includes(".default(") ||
					colDef.includes(".defaultNow()");

				columns.push({
					name: colName,
					type: colType,
					isNotNull,
					isArray,
					isPrimary,
					isAutoGenerated,
				});
			}
		}

		const foreignKeys = detectForeignKeys(variableName, columns, tableNames);

		tables.push({
			name: variableName,
			graphqlName: toGraphQLTypeName(variableName),
			columns,
			foreignKeys,
		});
	}

	return tables;
}

/**
 * GraphQL型を取得
 */
function getGraphQLType(column: ColumnInfo): string {
	const baseType = column.isNotNull
		? typeMapping[column.type] || "String!"
		: nullableTypeMapping[column.type] || "String";

	if (column.isArray) {
		const innerType = baseType.replace("!", "");
		return column.isNotNull ? `[${innerType}!]!` : `[${innerType}!]`;
	}

	return baseType;
}

/**
 * 除外するフィールドの定義
 * カスタムフィールドファイルで上書きするフィールドを除外
 */
const EXCLUDED_FIELDS: Record<string, Set<string>> = {
	BodyCondition: new Set([
		"weight",
		"bodyFat",
		"muscleMass",
		"skeletalMuscleRate",
		"bmi",
		"bmr",
		"avgSleepTime",
		"avgRespirationRate",
		"sympathetic",
		"parasympathetic",
		"bust",
		"underbust",
		"waist",
		"hip",
		"armCircumference",
		"buttockHeight",
		"thighCircumference",
		"calfCircumference",
		"ffd",
		"hwd",
	]),
	TrainerProfile: new Set([
		"signatureMuscle", // → signatureMuscles としてカスタムフィールドで定義
		"specialization", // → specializations としてカスタムフィールドで定義
	]),
};

/**
 * GraphQL型定義を生成
 */
function generateGraphQLType(table: TableInfo): string {
	const fields: string[] = [];
	const excludedFields = EXCLUDED_FIELDS[table.graphqlName] || new Set();

	// 基本フィールドのみ生成
	// リレーションフィールドは custom-fields.graphql で定義する
	for (const col of table.columns) {
		// 除外リストに含まれているフィールドはスキップ
		if (excludedFields.has(col.name)) {
			continue;
		}

		const graphqlType = getGraphQLType(col);
		fields.push(`\t${col.name}: ${graphqlType}`);
	}

	return `type ${table.graphqlName} {\n${fields.join("\n")}\n}`;
}

/**
 * カスタムフィールドファイルから定義されているQuery名を抽出
 */
function extractCustomQueryNames(customFieldsContent: string): Set<string> {
	const customQueries = new Set<string>();
	const queryRegex = /extend type Query \{([\s\S]*?)\}/;
	const match = customFieldsContent.match(queryRegex);
	if (match) {
		const queryBlock = match[1];
		const fieldRegex = /^\s*(\w+)\s*\(/gm;
		for (const fieldMatch of queryBlock.matchAll(fieldRegex)) {
			customQueries.add(fieldMatch[1]);
		}
	}
	return customQueries;
}

/**
 * Query型を生成
 */
function generateQueryType(
	tables: TableInfo[],
	customQueryNames: Set<string> = new Set(),
): string {
	const queries: string[] = [];

	// 各テーブルに対してQueryを生成
	for (const table of tables) {
		const queryName = toGraphQLQueryName(table.name);
		const typeName = table.graphqlName;

		// カスタムQueryが定義されている場合はスキップ
		if (customQueryNames.has(queryName)) {
			continue;
		}

		// 一覧取得
		queries.push(
			`\t${queryName}(limit: Int, offset: Int): [${typeName}!]!`,
		);

		// IDで取得（主キーがある場合）
		const primaryKey = table.columns.find((c) => c.isPrimary);
		if (primaryKey) {
			const byIdQueryName = `${queryName}ById`;
			if (!customQueryNames.has(byIdQueryName)) {
				queries.push(
					`\t${byIdQueryName}(${primaryKey.name}: Int!): ${typeName}`,
				);
			}
		}
	}

	return `type Query {\n${queries.join("\n")}\n}`;
}

/**
 * Mutation型を生成
 */
function generateMutationType(tables: TableInfo[]): string {
	const mutations: string[] = [];

	for (const table of tables) {
		const tableName = table.name.toLowerCase();
		const typeName = table.graphqlName;
		const inputName = `Create${table.graphqlName}Input`;

		// Create Mutation
		mutations.push(
			`\tcreate${table.graphqlName}(input: ${inputName}!): ${typeName}!`,
		);
	}

	return `type Mutation {\n${mutations.join("\n")}\n}`;
}

/**
 * カスタムフィールドファイルから定義されているInput型名を抽出
 */
function extractCustomInputNames(customFieldsContent: string): Set<string> {
	const customInputs = new Set<string>();
	const inputRegex = /^input (Create\w+Input)/gm;
	for (const match of customFieldsContent.matchAll(inputRegex)) {
		customInputs.add(match[1]);
	}
	return customInputs;
}

/**
 * Input型を生成
 */
function generateInputType(
	table: TableInfo,
	customInputNames: Set<string> = new Set(),
): string {
	// カスタムInput型が定義されている場合はスキップ
	const inputName = `Create${table.graphqlName}Input`;
	if (customInputNames.has(inputName)) {
		return "";
	}

	const fields: string[] = [];

	for (const col of table.columns) {
		// 自動生成されるフィールドは除外
		if (col.isAutoGenerated && col.isPrimary) {
			continue;
		}

		// default()があるフィールドは除外（自動生成される）
		// ただし、notNull()でない場合は含める（オプショナルなデフォルト値）
		if (col.isAutoGenerated && col.isNotNull) {
			continue;
		}

		// createdAt, updatedAtは除外（自動設定）
		if (col.name === "createdAt" || col.name === "updatedAt") {
			continue;
		}

		// keyフィールドはUUIDで自動生成されるため除外
		if (col.name === "key" && col.type === "uuid") {
			continue;
		}

		const graphqlType = getGraphQLType(col);
		fields.push(`\t${col.name}: ${graphqlType}`);
	}

	if (fields.length === 0) {
		return "";
	}

	return `input ${inputName} {\n${fields.join("\n")}\n}`;
}

/**
 * メイン処理
 */
async function main() {
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = path.dirname(__filename);
	const projectRoot = path.resolve(__dirname, "..");
	const schemaPath = path.join(projectRoot, "src/db/schema.ts");
	const customFieldsPath = path.join(
		projectRoot,
		"src/lib/graphql/schema/custom-fields.graphql",
	);
	const outputPath = path.join(
		projectRoot,
		"src/lib/graphql/schema/schema.graphql",
	);

	console.log("📖 Drizzleスキーマを読み込み中...");
	const schemaContent = fs.readFileSync(schemaPath, "utf-8");

	console.log("🔍 テーブル定義をパース中...");
	const tables = parseSchemaFile(schemaContent);

	console.log(`📋 ${tables.length}個のテーブルを検出しました`);
	for (const table of tables) {
		console.log(
			`   - ${table.name} -> ${table.graphqlName} (外部キー: ${table.foreignKeys.length}個)`,
		);
	}

	// カスタムフィールドファイルからQuery名とInput型名を抽出
	let customQueryNames = new Set<string>();
	let customInputNames = new Set<string>();
	if (fs.existsSync(customFieldsPath)) {
		const customFieldsContent = fs.readFileSync(customFieldsPath, "utf-8");
		customQueryNames = extractCustomQueryNames(customFieldsContent);
		customInputNames = extractCustomInputNames(customFieldsContent);
		console.log(
			`🔍 カスタムQuery ${customQueryNames.size}個を検出: ${Array.from(customQueryNames).join(", ")}`,
		);
		console.log(
			`🔍 カスタムInput型 ${customInputNames.size}個を検出: ${Array.from(customInputNames).join(", ")}`,
		);
	}

	// GraphQLスキーマを生成
	const header = `# ============================================
# 自動生成されたGraphQLスキーマ
# 生成元: src/db/schema.ts (Drizzle ORM)
#
# Database-Firstアプローチ:
# - DrizzleスキーマがSingle Source of Truth
# - このファイルは自動生成されるため、手動編集は推奨されません
# - カスタマイズが必要な場合は、scripts/generate-graphql-schema-from-db.ts を編集してください
#
# 生成日時: ${new Date().toISOString()}
# ============================================

`;

	// Query型
	const queryType = generateQueryType(tables, customQueryNames);

	// Mutation型
	const mutationType = generateMutationType(tables);

	// 型定義
	const types = tables.map(generateGraphQLType).join("\n\n");

	// Input型
	const inputTypes = tables
		.map((table) => generateInputType(table, customInputNames))
		.filter((input) => input !== "")
		.join("\n\n");

	const output =
		header +
		queryType +
		"\n\n" +
		mutationType +
		"\n\n" +
		types +
		"\n\n" +
		inputTypes;

	// カスタムフィールドファイルをマージ
	let finalOutput = output;
	if (fs.existsSync(customFieldsPath)) {
		console.log("🔗 カスタムフィールドをマージ中...");
		const customFields = fs.readFileSync(customFieldsPath, "utf-8");
		finalOutput = output + "\n\n" + customFields;
	} else {
		console.log("ℹ️  カスタムフィールドファイルが見つかりません（スキップ）");
	}

	console.log("📝 GraphQLスキーマを書き出し中...");
	fs.writeFileSync(outputPath, finalOutput);

	console.log(`✅ 完了: ${outputPath}`);
	console.log("");
	console.log("📌 次のステップ:");
	console.log("   1. 生成されたスキーマを確認してください");
	console.log("   2. npm run codegen を実行して型を生成してください");
	console.log("   3. 必要に応じてリゾルバーを実装してください");
}

main().catch(console.error);

